### ISSUE TITLE
production and development builds 

### ISSUE THREAD

**Issue by ericorruption** [ericorruption/static-boilerplate#100]
so that we can correctly hash static files. (This did not work out well on every file change.)

**Comment by ericorruption** [comment]
@gibatronic @evandroeisinger what's your opinion on having a different build for prd and dev environments?

Currently I just treat both builds as a single thing, and I think some of my problems are caused by that.

**Comment by evandroeisinger** [comment]
Normally I've two taks:
- One for development process, which has all subtasks that I use to develop the project;
- Another for distribution, which made all the build process;

**Comment by gibatronic** [comment]
yea, and your `serve` task should check on `NODE_ENV` to determine if it's going to make a development build or a production one. but also give that option through tasks like `serve:dev` and `serve:prd`. and the same could be made for the `build` task as well.

**Comment by ericorruption** [comment]
Ignored in favor of parcels' dev/watch task and real builds only for PRD
